config/routes.rb
Rails.application.routes.draw do
  get 'order/index'
  get 'order/new'
  get 'order/show'
  post 'order/update'
  get 'completion', to: 'completion#index'
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :shops
  resources :order_items
  resources :cards
  post '/checkout', to: 'checkout#create', as: 'checkout_create'
  resources :webhooks, only: [:create]

  root "shops#index"
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  def show
    @order_items=current_order.order_items
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards_item.html.erb
<br>
<div class="container my-5">
  <h1 style="background-color:blue; text-align:center;">Cart</h1>
  <% @order_items.each do |order_item| %>
    <div class="card mb-3">
      <div class="card-body">
        <h3 class="card-title">Product Name: <%= order_item.product.title %></h3>
        <h5 class="card-subtitle mb-2 text-muted">Product Price: <%= order_item.product.price %></h5>

        <%= form_for order_item, remote: true do |f| %>
          <%= f.hidden_field :product_id, value: order_item.product.id %>
          <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control mb-2" %>
          <%= f.submit "Update Cart", class: "btn btn-outline-warning" %>
        <% end %>
        <%# <%= button_to "Buy now!", checkout_create_path, params: { id: order_item.product.id }, class: "btn btn-outline-success my-2", data: { turbo: false } %> 
        <%= button_to "Remove Items", order_item_path(order_item), method: :delete, remote: true, class: "btn btn-outline-danger my-2" %>
        <h2>Total: <%= order_item.total %></h2>
        <%= link_to "proceed to payment", order_show_path(order_id: @order_items.first.order_id) , class: "btn btn-outline-info my-2" %>

      </div>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Your current card value has a subtotal of: <%= current_order.subtotal %></h3>
    </div>
  </div>
</div>

app/views/cards/_create.html.erb
<h1><%= link_to "#{current_order.order_items.size} items in Cart with a value of:- $#{current_order.subtotal}", card_path(id: 1),class:"btn btn-info" %></h1>

app/views/cards/show.html.erb
<div id="card-item">
  <%= render 'cards_item'%>
</div>