config/routes.rb
Rails.application.routes.draw do
  get 'order/index'
  get 'order/new'
  get 'order/show'
  post 'order/update'
  get 'completion', to: 'completion#index'
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :shops
  resources :order_items
  resources :cards
  post '/checkout', to: 'checkout#create', as: 'checkout_create'
  resources :webhooks, only: [:create]

  root "shops#index"
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
      @order_item = OrderItem.new
      @products = Product.where("title ILIKE ?", "%#{params[:filter]}%")
    end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to root_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price,)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
   <div>
    <%= form.label :cotegory, style: "display: block" %>
    <%= form.text_field :cotegory %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="container my-5">
  <p style="color: green"><%= notice %></p>
  <hr>
  <h1 style="background-color: blue; text-align: center">Products</h1>
  <hr>
  <div id="products" class="mx-3">
    <% @products.each do |product| %>
      <div id="<%= dom_id product %>">
        <p>
          <strong>Title:</strong>
          <%= product.title %>
        </p>
        <p>
          <strong>Price:</strong>
          <%= product.price %>
        </p>
         <p>
          <strong>Sales Count:</strong>
          <%= product.sales_count %>
        </p>
        <%= link_to "Show this product", shop_path(product) %>
        <p>
          <%= form_for @order_item, remote: true, url: order_items_path do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.number_field :quantity, min: 1 %>
            <%= f.submit "Add to Cart" %>
          <% end %>
        </p>
        <hr>
      </div>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <div class="min-w-full my-8">
    <%= turbo_frame_tag "new-product-form", src: new_product_path %>
    <%= turbo_frame_tag "product" do %>
      <%= render @products %>
    <% end %>
  </div>
</div>
    <div id="card">
    <%= render "cards/create" %>
  </div>

app/views/products/new.html.erb
<div style="text-align:center",class="mx-5 my-5">
    <h1>New product</h1>

    <%= render "form", product: @product %>

    <br>

    <div>
      <%= link_to "Back to products", products_path %>
    </div>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>